### ISSUE TITLE
Mask overlap issues with green bar

### ISSUE THREAD

**Issue by gswong** [PeachTreeOath/LD40#100]

**Comment by gswong** [comment]
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5711aca4f100e30e008e0cab/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51a27922d7e77aeb462d075d5a1bac415a5910a9ffd87da2a42062c80d55b98e30063e937f03a6aa8318b500bf21894c81beb88f48c4ed3e37aa.PNG)

**Comment by PeachTreeOath** [comment]
man I've looked at this tut too
