### ISSUE TITLE
Figure out new Unity tile system for building levels

### ISSUE THREAD

**Issue by PeachTreeOath** [PeachTreeOath/LD40#7]

**Comment by gswong** [comment]
![palette.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5711aca4f100e30e008e0cab/125516c66e82c728ace21e0d46f89596269697accda5fd53b652fa912a5265296b51a27922d7e77aeb462d075d5a1bac415a5910a9ffd87da2a42062c80d55b98e30063e937f03a6aa801fb500bf21894d85bfb58c49c6ef3b37aa.png)

**Comment by gswong** [comment]
![palette2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5711aca4f100e30e008e0cab/125516c66e82c728ace21e0d46f89596269697acddabf301b44fff9e2c4533317346f62a22d7b12ced167f57095d4bf941585d42a8ac8f7af0b22e6c981e5ab38532022d8c6853beb2901eb70bbb258a4d87b7bc8a4bc8ea3b2df5c6.png)

**Comment by gswong** [comment]
Tile Palette is like your color palette.
Active Tilemap is like your layer.
Use paint brush tool to paint in the selected layer.
